pullRequestReview: true
ignore: 
  urls: # Array of url to ignore
    - https://www.linkedin.com/in/nadiamedkouri  #myterious reason the link return a 999
    -  https://leetcode.com #website hates the crawler
    -  https://www.udemy.com #website hates the crawler
